---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Add i386 architecture
      raw: dpkg --print-foreign-architectures | grep "i386" || dpkg --add-architecture i386

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: css
  remote_user: root
  tasks: 

    - name: Save license
      raw: echo "steamcmd steam/question string {{ steam_license }}" >/tmp/selections

    - name: Agree to license 
      raw: echo "steamcmd steam/question string {{ steam_license }}" | debconf-set-selections

    - name: Install steamcmd
      apt:
        name: steamcmd
        state: present
        allow_unauthenticated: yes
      